import { MajorInfo, AdmissionWave, StudentRegistration, SchoolActivityItem, ActivityVideoItem } from '../types/spmb';

export const SCHOOL_INFO = {
  name: 'SMK Islam Tanfirul Ghoyyi',
  foundation: 'Yayasan Pondok Pesantren Tanfirul Ghoyyi',
  subBrand: "Sekolah Berbasis Al-Qur'an & Bahasa",
  shortName: 'SMK TANGO',
  accreditation: 'Terakreditasi Baik Sekali',
  npsn: '20569842',
  principal: 'Sahal Mahfud, S.Pd., M.Pd.',
  academicYear: '2027-2028',
  address: 'Jalan Sunan Giri, Groyok Sukorejo Lamongan, PP. Tanfirul Ghoyyi',
  city: 'Lamongan',
  province: 'Jawa Timur',
  phone: '0322 326056',
  whatsapp: '085230693727',
  whatsappFormatted: '6285230693727',
  registrationBitly: 'https://bit.ly/SPMB-SMKTG-2027-2028',
  registrationBitlyDisplay: 'bit.ly/SPMB-SMKTG-2027-2028',
  email: 'info@smkitg.sch.id',
  website: 'www.smkitg.sch.id',
  instagram: '@smkitg',
  motto1: 'Sekolah Tahfidz dan Dakwah Lewat Digital',
  motto2: "Unggul dalam Prestasi, Berkarakter Qur'ani, Siap Bersinergi di Era Digital",
};

// ONLY 1 MAJOR: Desain Komunikasi Visual (DKV)
export const MAJORS_DATA: MajorInfo[] = [
  {
    code: 'DKV',
    name: 'Desain Komunikasi Visual (DKV)',
    shortDesc: 'Satu-satunya program keahlian unggulan berfokus pada multimedia kreatif, dakwah digital, videografi, dan desain grafis profesional.',
    fullDesc: 'Program Keahlian Desain Komunikasi Visual (DKV) SMK Islam Tanfirul Ghoyyi memadukan keterampilan industri kreatif modern (Adobe Creative Cloud, UI/UX, Motion Graphics, Studio Fotografi & Video Editing) dengan nilai-nilai dakwah digital Qur\'ani, kemampuan bahasa Inggris aktif, serta etika santri. Menghasilkan lulusan desainer, videografer, content creator, dan technopreneur yang berkarakter.',
    quota: 72,
    enrolled: 46,
    color: 'emerald',
    badge: 'Program Keahlian Tunggal Unggulan',
    image: '/src/assets/images/dkv_creative_studio_1790125899423.jpg',
    isMarquee: true,
    careerOutlooks: [
      'Graphic & UI/UX Designer',
      'Videographer & Content Creator Media Sosial',
      'Studio Photographer & Digital Retoucher',
      'Motion Graphic & 2D Animator',
      'Digital Marketing & Brand Strategist',
      'Wirausaha Agensi Kreatif / Percetakan Digital',
    ],
    keySubjects: [
      'Dasar Desain Grafis & Tipografi (Latin & Arab)',
      'Fotografi Studio & Lighting Komersial',
      'Videografi & Audio-Visual Editing (Premiere, After Effects)',
      'Digital Illustration & Vector Art',
      'Dakwah Lewat Digital & Social Media Management',
      'English for Creative Media & Communication',
    ],
    certifications: [
      'Sertifikat Kompetensi BNSP Skema Desain Komunikasi Visual Level II',
      'Sertifikat Penguasaan Software Industri Kreatif',
      'Portofolio Digital Karya Terakreditasi Asosiasi Profesi',
    ],
    concentrations: [
      'Desain Grafis & Digital Branding',
      'Videografi, Sinematografi & Motion Design',
      'Fotografi Komersial & Editorial Studio',
      'Dakwah Digital, Kaligrafi & Konten Kreatif Islam',
    ],
  },
];

// Waktu Pendaftaran SPMB T.P 2027-2028
export const ADMISSION_WAVES: AdmissionWave[] = [
  {
    id: 'wave-indent',
    key: 'indent',
    name: 'Jalur Indent',
    period: '1 September s/d 31 Desember 2026',
    startDate: '2026-09-01',
    endDate: '2026-12-31',
    promo: 'Gratis 100% Paket Seragam',
    discountNote: 'Bebas biaya 4 stel seragam sekolah lengkap + jas almamater',
    isActive: true,
    benefits: [
      'GRATIS 100% Paket Seragam Lengkap (4 stel + Jas Almamater)',
      'Bebas biaya pendaftaran dan administrasi seleksi',
      'Jaminan prioritas kuota utama Jurusan DKV',
      'Prioritas penempatan kamar asrama santri pondok',
    ],
  },
  {
    id: 'wave-1',
    key: 'gelombang1',
    name: 'Gelombang 1',
    period: '1 Januari s/d 31 Maret 2027',
    startDate: '2027-01-01',
    endDate: '2027-03-31',
    promo: 'Potongan 50% Paket Seragam',
    discountNote: 'Diskon 50% biaya paket seragam sekolah',
    isActive: false,
    benefits: [
      'Potongan 50% biaya paket seragam sekolah lengkap',
      'Bimbingan portofolio dan peminatan studio DKV gratis',
      'Akses workshop multimedia sebelum masuk KBM',
    ],
  },
  {
    id: 'wave-2',
    key: 'gelombang2',
    name: 'Gelombang 2',
    period: '1 April s/d 30 Juni 2027',
    startDate: '2027-04-01',
    endDate: '2027-06-30',
    promo: 'Pendaftaran Reguler',
    discountNote: 'Sesuai dengan sisa kuota yang masih tersedia',
    isActive: false,
    benefits: [
      'Pendaftaran reguler seleksi Jurusan DKV',
      'Tes minat bakat dan wawancara komitmen santri',
      'Penerimaan berdasarkan sisa kuota siswa',
    ],
  },
];

// Cara Pendaftaran: Scan Barcode atau Ketik Link dengan Menyertakan 3 Berkas
export const REQUIRED_DOCUMENTS = [
  {
    id: 'fcKK',
    name: 'Fotokopi Kartu Keluarga (FC KK)',
    desc: 'Fotokopi KK terbaru yang memuat nama calon siswa dan orang tua/wali.',
    mandatory: true,
  },
  {
    id: 'nisn',
    name: 'NISN (Nomor Induk Siswa Nasional)',
    desc: 'Bukti NISN 10 digit aktif yang terdaftar di database Kemendikbud/Kemenag.',
    mandatory: true,
  },
  {
    id: 'aktaKelahiran',
    name: 'Akta Kelahiran',
    desc: 'Fotokopi Akta Kelahiran calon siswa yang dikeluarkan Dispendukcapil.',
    mandatory: true,
  },
];

// Kegiatan Santri: Harian, Bulanan, Tahunan
export const SCHOOL_ACTIVITIES: SchoolActivityItem[] = [
  // 1. Kegiatan Harian
  {
    name: 'Lalaran Alfiyah',
    timeframe: 'harian',
    arabicTitle: 'لَلَرَانْ أَلْفِيَّة ابْن مَالِك',
    shortDesc: 'Melantunkan dan menghafal bait-bait nadhom Alfiyah Ibnu Malik bersama-sama ba\'da Maghrib/Subuh.',
    details: 'Pembiasaan melantunkan nadhom kaidah gramatika Arab Alfiyah untuk menanamkan pemahaman mendalam tentang tata bahasa bahasa Arab dan melatih daya ingat santri.',
    iconName: 'BookMarked',
  },
  {
    name: 'Tartil Qur\'an',
    timeframe: 'harian',
    arabicTitle: 'تَرْتِيْلُ الْقُرْآنِ الْكَرِيْم',
    shortDesc: 'Bimbingan membaca Al-Qur\'an dengan makharijul huruf dan hukum tajwid yang tepat berstandar sanad.',
    details: 'Setiap hari santri dibina oleh asatidz bersanad untuk memperbaiki fashohah, makhorijul huruf, dan hukum tajwid sehingga bacaan Al-Qur\'an fasih dan merdu.',
    iconName: 'BookOpen',
  },
  {
    name: 'Setoran Hafalan Al-Qur\'an',
    timeframe: 'harian',
    arabicTitle: 'تَسْمِيْعُ حِفْظِ الْقُرْآن',
    shortDesc: 'Ziyadah (tambah hafalan baru) dan muroja\'ah hafalan secara talaqqi berhadapan dengan ustadz/ustadzah.',
    details: 'Mendukung visi Sekolah Berbasis Al-Qur\'an dengan target hafalan terukur yang disesuaikan dengan kemampuan santri program reguler maupun asrama.',
    iconName: 'CheckCircle2',
  },
  {
    name: 'English Class',
    timeframe: 'harian',
    arabicTitle: 'Kelas Bahasa Inggris Aktif',
    shortDesc: 'Latihan percakapan bahasa Inggris terapan untuk industri media, presentasi, dan teknologi kreatif.',
    details: 'Santri dilatih conversation, creative copywriting, vocabulary media digital, dan public presentation dalam bahasa Inggris untuk siap bersaing global.',
    iconName: 'Languages',
  },

  // 2. Kegiatan Bulanan
  {
    name: 'Munaqosah',
    timeframe: 'bulanan',
    arabicTitle: 'الْمُنَاقَشَةُ الشَّهْرِيَّة',
    shortDesc: 'Ujian komprehensif evaluasi capaian hafalan Al-Qur\'an dan nadhom Alfiyah di hadapan dewan penguji.',
    details: 'Evaluasi bulanan untuk mengukur kualitas dan kelancaran hafalan santri dengan pemberian raport tahfidz dan nadhom.',
    iconName: 'Award',
  },
  {
    name: 'Khitobah',
    timeframe: 'bulanan',
    arabicTitle: 'خِطَابَةُ الْمِنْبَرِيَّة (Public Speaking)',
    shortDesc: 'Latihan pidato dan retorika dakwah dalam 3 bahasa (Bahasa Arab, Inggris, dan Indonesia).',
    details: 'Santri tampil bergiliran di podium untuk mengasah keberanian public speaking, seni berdakwah, dan kepemimpinan di hadapan seluruh santri.',
    iconName: 'Mic',
  },
  {
    name: 'Istighosah',
    timeframe: 'bulanan',
    arabicTitle: 'اِسْتِغَاثَة جَمَاعِيَّة',
    shortDesc: 'Doa bersama memohon pertolongan Allah SWT, keberkahan ilmu, dan kemudahan ujian siswa.',
    details: 'Majelis dzikir dan munajat yang dipimpin oleh pengasuh pesantren untuk menyucikan hati dan mempererat ukhuwah islamiyah.',
    iconName: 'HeartHandshake',
  },
  {
    name: 'Ziarah Muassis',
    timeframe: 'bulanan',
    arabicTitle: 'زِيَارَةُ الْمُؤَسِّسِيْن وَالْأَوْلِيَاء',
    shortDesc: 'Ziarah ke maqbaroh pendiri pesantren Tanfirul Ghoyyi dan para auliya\' di wilayah Lamongan & sekitarnya.',
    details: 'Meneladani akhlak, keikhlasan, dan perjuangan para perintis dakwah Islam serta mendoakan para sesepuh pesantren.',
    iconName: 'Compass',
  },
  {
    name: 'Seminar Workshop',
    timeframe: 'bulanan',
    arabicTitle: 'Workshop Kreatif DKV & Dakwah Digital',
    shortDesc: 'Pelatihan intensif mendatangkan narasumber profesional praktisi desain, videografi, dan media kreatif.',
    details: 'Menghadirkan alumni sukses, praktisi rumah produksi, fotografer profesional, dan pegiat dakwah digital untuk upgrade skill santri.',
    iconName: 'Presentation',
  },
  {
    name: 'Manaqib',
    timeframe: 'bulanan',
    arabicTitle: 'مَنَاقِبُ الشَّيْخِ عَبْدِ الْقَادِرِ الْجَيْلَانِيّ',
    shortDesc: 'Pembacaan kisah keteladanan Syaikh Abdul Qadir Al-Jailani r.a. dilanjutkan doa bersama.',
    details: 'Tradisi spiritual bulanan untuk memperkuat mahabbah kepada para kekasih Allah dan menyerap keteladanan budi pekerti luhur.',
    iconName: 'Sparkles',
  },

  // 3. Kegiatan Tahunan
  {
    name: 'Kunjungan Industri',
    timeframe: 'tahunan',
    arabicTitle: 'Industrial Visit DKV',
    shortDesc: 'Kunjungan edukasi studi lapangan ke stasiun televisi, studio animasi, periklanan, dan penerbitan nasional.',
    details: 'Santri DKV melihat langsung alur kerja industri profesional, teknologi kamera bioskop, sistem rendering animasi, dan manajemen agensi media.',
    iconName: 'Building2',
  },
  {
    name: 'Praktek Kerja Lapangan (PKL)',
    timeframe: 'tahunan',
    arabicTitle: 'Internship / On-the-Job Training',
    shortDesc: 'Magang kerja langsung di industri kreatif, percetakan digital, dan media massa selama 3-6 bulan.',
    details: 'Menerapkan seluruh keahlian DKV di dunia kerja nyata bersama mitra Dunia Usaha dan Dunia Industri (DUDI) untuk mengantongi sertifikat industri.',
    iconName: 'Briefcase',
  },
];

// Seed Students Data for demo (all taking DKV)
export const SAMPLE_STUDENTS: StudentRegistration[] = [
  {
    id: 'TG-2027-0001',
    nisn: '0087451201',
    nik: '3524021204090001',
    fullName: 'Achmad Fauzan Robbani',
    gender: 'L',
    birthPlace: 'Lamongan',
    birthDate: '2009-04-12',
    religion: 'Islam',
    studentPhone: '081234567890',
    studentEmail: 'fauzan.robbani@gmail.com',
    address: 'Dusun Sukorejo RT 02 RW 01',
    district: 'Lamongan',
    regency: 'Lamongan',
    previousSchool: 'MTs Negeri 1 Lamongan',
    majorFirst: 'DKV',
    programType: 'pesantren',
    track: 'indent',
    wave: 'indent',
    fatherName: 'H. Abdul Ghofur',
    motherName: 'Hj. Siti Aminah',
    parentPhone: '081234567891',
    parentJob: 'Wiraswasta',
    parentIncome: 'Rp 3.000.000 - Rp 5.000.000',
    averageScore: 89.2,
    achievements: 'Hafal 3 Juz Al-Qur\'an & Juara 1 Desain Kaligrafi Digital Kabupaten Lamongan',
    documents: {
      fcKKName: 'fc_kk_fauzan.pdf',
      nisnDocName: 'dokumen_nisn_0087451201.pdf',
      aktaKelahiranName: 'akta_fauzan.pdf',
    },
    status: 'lulus',
    testSchedule: {
      date: '2026-11-20',
      time: '08:00 - 11:30 WIB',
      room: 'Studio DKV SMK Tango',
      examiner: 'Sahal Mahfud, S.Pd., M.Pd. & Ustadz Ahmad',
      subjects: ['Tartil Al-Qur\'an', 'English Speaking Basics', 'Portofolio Desain DKV'],
    },
    verificationNotes: 'Berkas FC KK, NISN, dan Akta Kelahiran lengkap dan terverifikasi. Berhak atas Gratis 100% Paket Seragam (Jalur Indent).',
    registeredAt: '2026-09-15',
  },
  {
    id: 'TG-2027-0002',
    nisn: '0091245892',
    nik: '3524035607090002',
    fullName: 'Nabila Zahra Syahrani',
    gender: 'P',
    birthPlace: 'Lamongan',
    birthDate: '2009-07-25',
    religion: 'Islam',
    studentPhone: '082134567891',
    studentEmail: 'nabila.zahra@gmail.com',
    address: 'Jl. Veteran No. 45',
    district: 'Lamongan',
    regency: 'Lamongan',
    previousSchool: 'SMP Plus Al-Hidayah',
    majorFirst: 'DKV',
    programType: 'pesantren',
    track: 'indent',
    wave: 'indent',
    fatherName: 'Bambang Supriyanto',
    motherName: 'Rini Astuti',
    parentPhone: '082134567892',
    parentJob: 'PNS Guru',
    parentIncome: 'Rp 5.000.000 - Rp 7.500.000',
    averageScore: 91.0,
    achievements: 'Hafal 4 Juz Al-Qur\'an & Juara Fotografi Pelajar',
    documents: {
      fcKKName: 'kk_nabila.pdf',
      nisnDocName: 'nisn_nabila.pdf',
      aktaKelahiranName: 'akta_nabila.pdf',
    },
    status: 'lulus',
    testSchedule: {
      date: '2026-11-20',
      time: '08:00 - 11:30 WIB',
      room: 'Studio DKV SMK Tango',
      examiner: 'Tim Penguji DKV & Asatidz',
      subjects: ['Tartil Al-Qur\'an', 'English Speaking', 'Wawancara DKV'],
    },
    verificationNotes: 'Diterima Jalur Indent dengan fasilitas 100% Gratis Paket Seragam.',
    registeredAt: '2026-09-22',
  },
  {
    id: 'TG-2027-0003',
    nisn: '0098712345',
    nik: '3524011210090003',
    fullName: 'Muhammad Rizqi Al-Farizi',
    gender: 'L',
    birthPlace: 'Gresik',
    birthDate: '2009-10-18',
    religion: 'Islam',
    studentPhone: '083812345678',
    studentEmail: 'rizqi.alfarizi@gmail.com',
    address: 'Dusun Randubener RT 01 RW 02',
    district: 'Duduksampeyan',
    regency: 'Gresik',
    previousSchool: 'SMP Negeri 1 Duduksampeyan',
    majorFirst: 'DKV',
    programType: 'pesantren',
    track: 'gelombang1',
    wave: 'gelombang1',
    fatherName: 'Mustofa',
    motherName: 'Khusnul Khotimah',
    parentPhone: '083812345679',
    parentJob: 'Petani Tambak',
    parentIncome: 'Rp 2.000.000 - Rp 3.000.000',
    averageScore: 84.5,
    achievements: 'Lancar membaca tartil Al-Qur\'an dan editing video TikTok dakwah',
    documents: {
      fcKKName: 'fc_kk_rizqi.pdf',
      nisnDocName: 'nisn_rizqi.pdf',
      aktaKelahiranName: 'akta_rizqi.pdf',
    },
    status: 'jadwal_tes',
    testSchedule: {
      date: '2027-01-25',
      time: '08:30 - 11:00 WIB',
      room: 'Lab Komputer DKV',
      examiner: 'Ustadz Munir & Pak Dian (DKV)',
      subjects: ['Tes Tartil Qur\'an', 'English Vocabulary Basics', 'Tes Minat Desain Visual'],
    },
    verificationNotes: 'Berkas FC KK, NISN, Akta lengkap. Mendapatkan Potongan 50% Paket Seragam (Gelombang 1).',
    registeredAt: '2027-01-05',
  },
  {
    id: 'TG-2027-0004',
    nisn: '0095567812',
    nik: '3524084501090004',
    fullName: 'Siti Nur Aisyah',
    gender: 'P',
    birthPlace: 'Lamongan',
    birthDate: '2009-01-30',
    religion: 'Islam',
    studentPhone: '085712345678',
    studentEmail: 'aisyah.nur@gmail.com',
    address: 'Desa Kramat RT 04 RW 02',
    district: 'Lamongan',
    regency: 'Lamongan',
    previousSchool: 'MTs Tanfirul Ghoyyi',
    majorFirst: 'DKV',
    programType: 'pesantren',
    track: 'indent',
    wave: 'indent',
    fatherName: 'H. Syamsul Arifin',
    motherName: 'Hj. Maryam',
    parentPhone: '085712345679',
    parentJob: 'Wiraswasta',
    parentIncome: 'Rp 4.000.000 - Rp 6.000.000',
    averageScore: 88.0,
    achievements: 'Hafal 500 bait Alfiyah Ibnu Malik & 2 Juz Al-Qur\'an',
    documents: {
      fcKKName: 'kk_aisyah.pdf',
      nisnDocName: 'nisn_aisyah.pdf',
      aktaKelahiranName: 'akta_aisyah.pdf',
    },
    status: 'lulus',
    testSchedule: {
      date: '2026-11-20',
      time: '08:00 - 11:30 WIB',
      room: 'Studio DKV',
      examiner: 'Dewan Penguji SPMB',
      subjects: ['Uji Hafalan Qur\'an & Alfiyah', 'English Basics', 'Wawancara'],
    },
    verificationNotes: 'Prestasi istimewa Alfiyah Ibnu Malik. Diterima Jalur Indent (Gratis Paket Seragam).',
    registeredAt: '2026-09-18',
  },
  {
    id: 'TG-2027-0005',
    nisn: '0093321456',
    nik: '3524102203090005',
    fullName: 'Dimas Aditya Maulana',
    gender: 'L',
    birthPlace: 'Lamongan',
    birthDate: '2009-03-22',
    religion: 'Islam',
    studentPhone: '085230693727',
    studentEmail: 'dimas.aditya@gmail.com',
    address: 'Jalan Sunan Giri, Groyok Sukorejo Lamongan',
    district: 'Lamongan',
    regency: 'Lamongan',
    previousSchool: 'SMP Negeri 2 Lamongan',
    majorFirst: 'DKV',
    programType: 'reguler',
    track: 'gelombang1',
    wave: 'gelombang1',
    fatherName: 'Drs. H. Mulyono',
    motherName: 'Endang Wahyuni',
    parentPhone: '085230693727',
    parentJob: 'Karyawan Swasta',
    parentIncome: 'Rp 3.500.000 - Rp 5.000.000',
    averageScore: 82.5,
    achievements: 'Peminat Videografi dan Editing Konten YouTube',
    documents: {
      fcKKName: 'fc_kk_dimas.pdf',
      nisnDocName: 'nisn_dimas.pdf',
      aktaKelahiranName: 'akta_dimas.pdf',
    },
    status: 'menunggu_verifikasi',
    verificationNotes: 'Menunggu konfirmasi verifikasi fisik berkas (FC KK, NISN, Akta Kelahiran) di sekretariat SPMB.',
    registeredAt: '2027-01-12',
  },
];

export const INITIAL_STUDENTS: StudentRegistration[] = SAMPLE_STUDENTS;

export interface StudentAchievement {
  id: string;
  studentName: string;
  grade: string;
  major: string;
  title: string;
  event: string;
  level: 'Nasional' | 'Provinsi' | 'Kabupaten';
  medal: 'Emas (Juara 1)' | 'Perak (Juara 2)' | 'Perunggu (Juara 3)';
  year: string;
  category: 'Kejuruan DKV' | 'Tahfidz & Keagamaan' | 'Olimpiade Sains & IT' | 'Kreatif & Seni';
  description: string;
  image: string;
  organizer: string;
}

export const STUDENT_ACHIEVEMENTS: StudentAchievement[] = [
  {
    id: 'ach-risma',
    studentName: 'Dwi Rizma Atika Putri',
    grade: 'Siswi SMK Islam Tanfirul Ghoyyi',
    major: 'Desain Komunikasi Visual (DKV)',
    title: 'Juara 1 Lomba Melukis & Mewarnai Tingkat Nasional',
    event: 'Lomba Melukis & Mewarnai Tingkat Nasional',
    level: 'Nasional',
    medal: 'Emas (Juara 1)',
    year: '2026',
    category: 'Kreatif & Seni',
    description: 'Selamat & Sukses atas diraihnya Juara 1 Tingkat Nasional Lomba Melukis & Mewarnai oleh Goldenbrain Indonesia. Siswi berkarakter, berprestasi, dan berakhlak mulia.',
    image: '/prestasi_risma_poster.jpg',
    organizer: 'Goldenbrain Indonesia',
  },
  {
    id: 'ach-atin',
    studentName: 'Zabrita Nur Suriyatin',
    grade: 'Siswi SMK Islam Tanfirul Ghoyyi',
    major: 'Desain Komunikasi Visual (DKV)',
    title: 'Juara 2 Olimpiade PAI Tingkat Nasional',
    event: 'Olimpiade Pendidikan Agama Islam (PAI) Tingkat Nasional',
    level: 'Nasional',
    medal: 'Perak (Juara 2)',
    year: '2026',
    category: 'Tahfidz & Keagamaan',
    description: 'Membawa pulang trofi bergengsi Juara 2 Olimpiade PAI Tingkat Nasional. Santriwati teladan dengan penguasaan materi keislaman dan pemahaman Qur\'ani unggul.',
    image: '/prestasi_zabrita_pai.jpg',
    organizer: 'Asosiasi Guru & Lembaga Pendidikan Agama Islam Nasional',
  },
  {
    id: 'ach-indira',
    studentName: 'Indira',
    grade: 'Siswi SMK Islam Tanfirul Ghoyyi',
    major: 'Desain Komunikasi Visual (DKV)',
    title: 'Juara 1 Tingkat Nasional Short Movie',
    event: 'Festival Sinematografi & Film Pendek Tingkat Nasional',
    level: 'Nasional',
    medal: 'Emas (Juara 1)',
    year: '2026',
    category: 'Kejuruan DKV',
    description: 'Meraih trofi emas Juara 1 Tingkat Nasional Short Movie (Film Pendek). Mengangkat pesan moral dan dakwah digital berkarakter santri lewat keahlian multimedia DKV.',
    image: '/prestasi_indira_film.jpg',
    organizer: 'Festival Film Pelajar & Komunitas Sinema Nasional',
  },
  {
    id: 'ach-1',
    studentName: 'Muhammad Fadhil Al-Ghozy',
    grade: 'Kelas XII DKV',
    major: 'Desain Komunikasi Visual (DKV)',
    title: 'Juara 1 Nasional (Medali Emas)',
    event: 'Lomba Keterampilan Siswa (LKS) SMK Tingkat Nasional',
    level: 'Nasional',
    medal: 'Emas (Juara 1)',
    year: '2026',
    category: 'Kejuruan DKV',
    description: 'Meraih medali emas kategori Graphic Design Technology & Branding Media Digital mengalahkan perwakilan dari 34 provinsi se-Indonesia.',
    image: '/prestasi_lks_nasional.jpg',
    organizer: 'Pusat Prestasi Nasional (Puspresnas) Kemendikbudristek RI',
  },
  {
    id: 'ach-2',
    studentName: 'Ahmad Zidni Mubarok',
    grade: 'Kelas XI DKV (Santri Tahfidz)',
    major: 'Desain Komunikasi Visual (DKV)',
    title: 'Juara 1 Tingkat Provinsi Jawa Timur',
    event: 'Musabaqah Hifdzil Qur\'an (MHQ) & Kaligrafi Islam Jawa Timur',
    level: 'Provinsi',
    medal: 'Emas (Juara 1)',
    year: '2026',
    category: 'Tahfidz & Keagamaan',
    description: 'Hafal 20 Juz Al-Qur\'an bersanad dan unggul dalam penilaian fashahah, tajwid mutqin, serta karya seni kaligrafi digital dekoratif.',
    image: '/prestasi_tahfidz_provinsi.jpg',
    organizer: 'Lembaga Pengembangan Tilawatil Qur\'an (LPTQ) Provinsi Jawa Timur',
  },
  {
    id: 'ach-3',
    studentName: 'Rizky Maulana & Annisa Nurul Fathimah',
    grade: 'Kelas XI DKV',
    major: 'Desain Komunikasi Visual (DKV)',
    title: 'Juara 1 Medali Emas & Juara 2 Medali Perak',
    event: 'Olimpiade Sains Terapan & Literasi Digital IT Pelajar',
    level: 'Kabupaten',
    medal: 'Emas (Juara 1)',
    year: '2026',
    category: 'Olimpiade Sains & IT',
    description: 'Memborong trofi juara dalam uji logika pemrograman dasar, desain antarmuka aplikasi interaktif, dan literasi digital sains.',
    image: '/prestasi_olimpiade_kabupaten.jpg',
    organizer: 'Dinas Pendidikan & Kemenag Kabupaten Lamongan',
  },
];

export const INITIAL_ACTIVITY_VIDEOS: ActivityVideoItem[] = [
  {
    id: 'vid-1',
    title: 'Lalaran Nadhom Alfiyah Ibnu Malik Santri SMK Islam Tanfirul Ghoyyi',
    category: 'Lalaran Alfiyah',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    thumbnailUrl: '/video_lalaran_alfiyah.jpg',
    duration: '04:15',
    dateAdded: '2026-09-15',
    description: 'Suasana syahdu dan khidmat lantunan bait-bait Nadhom Alfiyah Ibnu Malik santri putra dan putri di Pesantren Tanfirul Ghoyyi Lamongan.',
    speakerOrLead: 'Santri & Asatidz Ponpes Tanfirul Ghoyyi',
    tags: ['Lalaran Alfiyah', 'Kitab Kuning', 'Pesantren', 'Tradisi Santri'],
  },
  {
    id: 'vid-2',
    title: 'Praktek Produksi Short Movie & Cinematography Studio DKV',
    category: 'Praktek DKV',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    thumbnailUrl: '/prestasi_indira_film.jpg',
    duration: '06:30',
    dateAdded: '2026-09-10',
    description: 'Proses kreatif siswa Desain Komunikasi Visual mengoperasikan kamera cinema, lighting studio profesional, audio boom, dan editing pasca produksi.',
    speakerOrLead: 'Tim Multimedia & DKV SMK TANGO',
    tags: ['DKV', 'Short Movie', 'Sinematografi', 'Kreatif Digital'],
  },
  {
    id: 'vid-3',
    title: 'Bimbingan Tartil Al-Qur\'an & Ujian Setoran Tahfidz Bersanad',
    category: 'Tahfidz Al-Qur\'an',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    thumbnailUrl: '/prestasi_tahfidz_provinsi.jpg',
    duration: '05:45',
    dateAdded: '2026-08-28',
    description: 'Bimbingan rutin makharijul huruf, shifatul huruf, fashahah, serta setoran hafalan Juz 1 - 30 bersama ustadz/ustadzah pembina tahfidz.',
    speakerOrLead: 'Ustadz Pembina Tahfidz',
    tags: ['Tahfidz', 'Tartil', 'Hafalan Quran', 'Qurani'],
  },
  {
    id: 'vid-4',
    title: 'English Conversation Club & Public Speaking Competition',
    category: 'English Class',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    thumbnailUrl: '/prestasi_olimpiade_kabupaten.jpg',
    duration: '03:50',
    dateAdded: '2026-08-14',
    description: 'Latihan percakapan bahasa Inggris interaktif, debat santri, dan presentasi portofolio desain dalam bahasa Inggris.',
    speakerOrLead: 'English Mentor & Santri DKV',
    tags: ['English Class', 'Public Speaking', 'Conversation', 'Global Skill'],
  },
  {
    id: 'vid-5',
    title: 'Juara 1 Lomba Melukis Nasional — Dwi Rizma Atika Putri',
    category: 'Ekstrakurikuler',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    thumbnailUrl: '/prestasi_risma_poster.jpg',
    duration: '04:10',
    dateAdded: '2026-09-02',
    description: 'Sorotan karya dan wawancara bersama Dwi Rizma Atika Putri usai dinobatkan sebagai Juara 1 Nasional Lomba Melukis & Mewarnai oleh Goldenbrain Indonesia.',
    speakerOrLead: 'Dwi Rizma Atika Putri',
    tags: ['Prestasi Nasional', 'Melukis', 'Seni Grafis', 'Goldenbrain'],
  },
];

